<a href="https://colab.research.google.com/github/10172828/BIG-DATA/blob/main/ASS1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 6 3 2 1]


In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

equal = np.array_equal(arr1, arr2)

print(f"The arrays are equal: {equal}")


The arrays are equal: True


In [7]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


unique_values_x, counts_x = np.unique(x, return_counts=True)
most_frequent_value_x = unique_values_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_value_x)[0]

unique_values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_value_y = unique_values_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_value_y)[0]


print("For array x:")
print("Most frequent value:", most_frequent_value_x)
print("Indices:", indices_x)

print("\nFor array y:")
print("Most frequent value:", most_frequent_value_y)
print("Indices:", indices_y)

For array x:
Most frequent value: 1
Indices: [0 5 7 8 9]

For array y:
Most frequent value: 1
Indices: [0 1 2]


In [8]:
gfg = np.matrix('4 1 9; 12 3 1; 4 5 6')

# i sum of all elements
totalSum = np.sum(gfg)

# ii sum of all elements row
rowSum = np.sum(gfg, axis=1)

# iii sum of all elements column
columnSum = np.sum(gfg, axis=0)

print("Sum of all elements:", totalSum)
print("Sum of all elements row-wise:")
print(rowSum)

print("Sum of all elements column-wise:")
print(columnSum)

Sum of all elements: 45
Sum of all elements row-wise:
[[14]
 [16]
 [15]]
Sum of all elements column-wise:
[[20  9 16]]
